### ISSUE TITLE
Vapor + Jobs error on multiple JSONs

### ISSUE THREAD

**Issue by syky27** [BrettRToomey/Jobs#20]
Hi, I would like to use Jobs, however when I use this:

```
dependencies: [
        .Package(url: "https://github.com/vapor/vapor", majorVersion: 1, minor: 2),
        .Package(url: "https://github.com/BrettRToomey/Jobs.git", majorVersion: 0)
    ]
```

I get this from running `vapor xcode`

```
No Packages folder, fetch may take a while...
Fetching Dependencies [Failed]
Error: swift-package: error: multiple modules with the name JSON found
fix: modules should have a unique name across dependencies
```

I know you are using different JSON parser than Vapor, so how can I work around this name duplication?

**Comment by syky27** [comment]
I actually only need to use HTTP. So I modified my deps like this

```
    dependencies: [
        .Package(url: "https://github.com/vapor/engine", majorVersion: 1, minor: 2),
        .Package(url: "https://github.com/BrettRToomey/Jobs.git", majorVersion: 0)
    ]
```

But I still wonder how can I use both of these JSON deps when I want to use the one that ships with Vapor.

Thanks

**Comment by BrettRToomey** [comment]
Ahh! Good catch. I think I'll temporarily disable the json dependency and retag. This is mainly a swift package manager issue, but I'll talk with the authors and see what can be done.

**Comment by syky27** [comment]
I saw this reported in swift JIRA by Logan I think.
--
Tomas Sykora

**Comment by BrettRToomey** [comment]
Would you happen to have a link so I can go give it a thumbs up?

**Comment by syky27** [comment]
I might have been mistaken the only thing i can find is this https://bugs.swift.org/browse/SR-1195?jql=text%20~%20%22collision%22
--
Tomas Sykora

**Comment by BrettRToomey** [comment]
Okay, thanks! They need some sort of alias system.

**Comment by syky27** [comment]
Yeah, they do.
--
Tomas Sykora
